ssh_authorized_keys:
- "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDVC3AS/n9wSUeRsU1O5ZiMXos8sXKDHYQCoZbuAFQchekwfg7ZINAPiq1wPxPW8nEeVJe9Lgq6CufMKh29XNGeMsPfny6RnGSQ8Rgws5jmpHYNazjODPXbKo4PwtQljq7jvpZs3DDmtfteB5XhQW48pSuSkfurex/VZTq324TQLbYFV4DwAdwufFFvONS80qmXIlGDqE/lvOPfrzCfRY+z5vpasvuyYs6Voy0OEVQGcrpeWWiaG/uT5idMYfS4iLOCLh9dV1JYlKED7yPTZqZdd5SqoSI47WcSbPahLK1NUG4fP6c9eiHCDzFrPzx+9KhXtMTi8CZSkZkbVxZkSCuX ronblom@cs-rinis-562-tbe.rinis.nl"
write_files:
- encoding: ""
  content: |-
    #!/bin/bash
    #
    # add vlan
    vconfig add eth0 112
    # Get multus up-and-running
    mkdir -p /etc/cni/net.d/multus.d/
    ln -s /var/lib/rancher/k3s/agent/etc/cni/net.d/multus.d/multus.kubeconfig /etc/cni/net.d/multus.d/multus.kubeconfig
    cp /opt/cni/bin/multus $(grep bin_dir /var/lib/rancher/k3s/agent/etc/containerd/config.toml | awk -F '"' '{print $2}')
    # Cleanup ip's
    rm -rf /var/lib/cni/networks/cbr0/*
    rm -rf /var/lib/cni/multus/*
  owner: root
  path: /etc/local.d/networking.start
  permissions: '0755'
- encoding: ""
  content: |-
    #!/bin/bash
    ln -vs /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime
    echo 'Europe/Amsterdam' > /etc/timezone
  owner: root
  path: /etc/local.d/timezone.start
  permissions: '0755'
- encoding: ""
  content: |-
    /dev/cdrom	/media/cdrom	iso9660	noauto,ro 0 0
    /dev/usbdisk	/media/usb	vfat	noauto,ro 0 0
    /dev/sda1	/media/HD1TB	ext4	auto,rw   0 0
  owner: root
  path: /etc/fstab
  permissions: '0644'
boot_cmd:
- "mkdir /mnt/HD1TB || echo /mnt/HD1TB exists"
hostname: k3os

k3os:
  password: rancher
  k3s_args:
  - server
  - "--disable=traefik"
  modules:
  - nvme
  ntp_servers:
  - 0.nl.pool.ntp.org
  - 1.nl.pool.ntp.org