apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-110
spec: 
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": { "ips": true },
          "master": "enp2s0f0",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
                        { "dst": "192.168.111.0/24", "gw": "192.168.110.1" },
                        { "dst": "192.168.112.0/24", "gw": "192.168.110.1" },
                        { "dst": "192.168.113.0/24", "gw": "192.168.110.1" }
                ]
          }
        }, {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
      ]
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-112
spec: 
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": { "ips": true },
          "master": "vlan112",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
                        { "dst": "192.168.110.0/24", "gw": "192.168.112.1" },
                        { "dst": "192.168.111.0/24", "gw": "192.168.112.1" },
                        { "dst": "192.168.113.0/24", "gw": "192.168.112.1" }
                ]
          }
        }, {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
      ]
    }'

