apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "macvlan-112",
              "ips": [ "192.168.112.4/24" ],
              "mac": "c2:b0:57:49:47:f1",
              "gateway": [ "192.168.112.1" ]
            }]'
spec:
  containers:
  - name: samplepod
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine